import ProfilePictureOne from "../assets/images/notificationSideBarIcons/3D05.png";
import ProfilePictureTwo from "../assets/images/notificationSideBarIcons/Female05.png";
import ProfilePictureThree from "../assets/images/notificationSideBarIcons/3D08.png";
import ProfilePictureFour from "../assets/images/notificationSideBarIcons/Male07.png";
import ProfilePictureFive from "../assets/images/notificationSideBarIcons/Male11.png";

export const orderData = [
  {
    id: 2,
    orderId: "#CM9802",
    user: "Kate Morrison",
    project: "CRM Admin pages",
    address: "Larry San Francisco",
    date: "A minute ago",
    status: "Complete",
    profile: ProfilePictureTwo,
  },
  {
    id: 1,
    orderId: "#CM9801",
    user: "Natali Craig",
    project: "Landing Page",
    address: "Meadow Lane Oakland",
    date: "Just now",
    status: "In Progress",
    profile: ProfilePictureOne,
  },

  {
    id: 4,
    orderId: "#CM9804",
    user: "Orlando Diggs",
    project: "Admin Dashboard",
    address: "Washburn Baton Rouge",
    date: "Yesterday",
    status: "Approved",
    profile: ProfilePictureThree,
  },
  {
    id: 3,
    orderId: "#CM9803",
    user: "Drew Cano",
    project: "Client Project",
    address: "Bagwell Avenue Ocala",
    date: "1 hour ago",
    status: "Pending",
    profile: ProfilePictureTwo,
  },

  {
    id: 6,
    orderId: "#CM9801",
    user: "Natali Craig",
    project: "Landing Page",
    address: "Meadow Lane Oakland",
    date: "Just now",
    status: "In Progress",
    profile: ProfilePictureFive,
  },
  {
    id: 5,
    orderId: "#CM9805",
    user: "Andi Lane",
    project: "App Landing Page",
    address: "Nest Lane Olivette",
    date: "Feb 2, 2023",
    status: "Rejected",
    profile: ProfilePictureFour,
  },

  {
    id: 8,
    orderId: "#CM9803",
    user: "Drew Cano",
    project: "Client Project",
    address: "Bagwell Avenue Ocala",
    date: "1 hour ago",
    status: "Pending",
    profile: ProfilePictureThree,
  },
  {
    id: 7,
    orderId: "#CM9802",
    user: "Kate Morrison",
    project: "CRM Admin pages",
    address: "Larry San Francisco",
    date: "A minute ago",
    status: "Complete",
    profile: ProfilePictureTwo,
  },
  {
    id: 9,
    orderId: "#CM9804",
    user: "Orlando Diggs",
    project: "Admin Dashboard",
    address: "Washburn Baton Rouge",
    date: "Yesterday",
    status: "Approved",
    profile: ProfilePictureFour,
  },
  {
    id: 10,
    orderId: "#CM9805",
    user: "Andi Lane",
    project: "App Landing Page",
    address: "Nest Lane Olivette",
    date: "Feb 2, 2023",
    status: "Rejected",
    profile: ProfilePictureFive,
  },
];
